-- ============================================================
-- 生产管理服务 - 数据库迁移脚本
-- 服装工厂SaaS - 生产工单、工序路线、工位、生产任务、质检、报工
-- ============================================================

-- 1. 生产工单表
CREATE TABLE IF NOT EXISTS prod_production_order (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    order_no        VARCHAR(64)     NOT NULL COMMENT '工单编号',
    style_id        BIGINT          NOT NULL COMMENT '款式ID',
    style_code      VARCHAR(64)     NOT NULL COMMENT '款式编号',
    style_name      VARCHAR(128)    NOT NULL COMMENT '款式名称',
    sku_id          BIGINT          DEFAULT NULL COMMENT 'SKU ID',
    sku_code        VARCHAR(64)     DEFAULT NULL COMMENT 'SKU编号',
    customer_name   VARCHAR(128)    DEFAULT NULL COMMENT '客户名称',
    total_qty       INT             NOT NULL DEFAULT 0 COMMENT '计划生产总数',
    completed_qty   INT             NOT NULL DEFAULT 0 COMMENT '已完成数量',
    defective_qty   INT             NOT NULL DEFAULT 0 COMMENT '不良品数量',
    unit            VARCHAR(16)     NOT NULL DEFAULT '件' COMMENT '单位',
    delivery_date   DATE            DEFAULT NULL COMMENT '交货日期',
    start_date      DATE            DEFAULT NULL COMMENT '计划开始日期',
    end_date        DATE            DEFAULT NULL COMMENT '计划结束日期',
    priority        TINYINT         NOT NULL DEFAULT 0 COMMENT '优先级 0-普通 1-加急 2-特急',
    status          VARCHAR(32)     NOT NULL DEFAULT 'CREATED' COMMENT '状态: CREATED-已创建, APPROVED-已审批, IN_PROGRESS-生产中, SUSPENDED-暂停, COMPLETED-已完成, CLOSED-已关闭',
    remark          VARCHAR(512)    DEFAULT NULL COMMENT '备注',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    version         INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no, tenant_id),
    KEY idx_tenant_status (tenant_id, status),
    KEY idx_style_id (style_id),
    KEY idx_delivery_date (delivery_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产工单表';

-- 2. 工艺路线表
CREATE TABLE IF NOT EXISTS prod_process_route (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    route_code      VARCHAR(64)     NOT NULL COMMENT '路线编号',
    route_name      VARCHAR(128)    NOT NULL COMMENT '路线名称',
    style_id        BIGINT          DEFAULT NULL COMMENT '关联款式ID',
    description     VARCHAR(512)    DEFAULT NULL COMMENT '描述',
    status          VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE-启用, INACTIVE-停用',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    version         INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_route_code (route_code, tenant_id),
    KEY idx_tenant (tenant_id),
    KEY idx_style_id (style_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工艺路线表';

-- 3. 工序步骤表
CREATE TABLE IF NOT EXISTS prod_process_step (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    route_id        BIGINT          NOT NULL COMMENT '工艺路线ID',
    step_no         INT             NOT NULL COMMENT '工序序号',
    step_name       VARCHAR(128)    NOT NULL COMMENT '工序名称',
    step_type       VARCHAR(32)     NOT NULL DEFAULT 'SEWING' COMMENT '工序类型: CUTTING-裁剪, IRONING-熨烫, SEWING-缝制, PACKING-包装, QC-质检, OTHER-其他',
    standard_time   DECIMAL(10,2)   DEFAULT NULL COMMENT '标准工时(分钟)',
    standard_output INT             DEFAULT NULL COMMENT '标准产量(件/小时)',
    description     VARCHAR(512)    DEFAULT NULL COMMENT '工序说明',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    PRIMARY KEY (id),
    KEY idx_route_id (route_id),
    KEY idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工序步骤表';

-- 4. 工位表
CREATE TABLE IF NOT EXISTS prod_workstation (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    station_code    VARCHAR(64)     NOT NULL COMMENT '工位编号',
    station_name    VARCHAR(128)    NOT NULL COMMENT '工位名称',
    workshop        VARCHAR(64)     DEFAULT NULL COMMENT '车间',
    production_line VARCHAR(64)     DEFAULT NULL COMMENT '产线',
    station_type    VARCHAR(32)     NOT NULL DEFAULT 'SEWING' COMMENT '工位类型: CUTTING-裁剪, IRONING-熨烫, SEWING-缝制, PACKING-包装, QC-质检, OTHER-其他',
    worker_id       BIGINT          DEFAULT NULL COMMENT '当前绑定工人ID',
    worker_name     VARCHAR(64)     DEFAULT NULL COMMENT '当前绑定工人姓名',
    equipment_code  VARCHAR(64)     DEFAULT NULL COMMENT '设备编号',
    status          VARCHAR(32)     NOT NULL DEFAULT 'IDLE' COMMENT '状态: IDLE-空闲, BUSY-忙碌, MAINTENANCE-维护中, DISABLED-停用',
    remark          VARCHAR(512)    DEFAULT NULL COMMENT '备注',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    version         INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_station_code (station_code, tenant_id),
    KEY idx_tenant (tenant_id),
    KEY idx_workshop (workshop),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工位表';

-- 5. 生产任务表
CREATE TABLE IF NOT EXISTS prod_production_task (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    task_no         VARCHAR(64)     NOT NULL COMMENT '任务编号',
    order_id        BIGINT          NOT NULL COMMENT '生产工单ID',
    route_id        BIGINT          DEFAULT NULL COMMENT '工艺路线ID',
    step_id         BIGINT          NOT NULL COMMENT '工序步骤ID',
    step_name       VARCHAR(128)    NOT NULL COMMENT '工序名称',
    station_id      BIGINT          DEFAULT NULL COMMENT '分配工位ID',
    station_name    VARCHAR(128)    DEFAULT NULL COMMENT '工位名称',
    worker_id       BIGINT          DEFAULT NULL COMMENT '工人ID',
    worker_name     VARCHAR(64)     DEFAULT NULL COMMENT '工人姓名',
    plan_qty        INT             NOT NULL DEFAULT 0 COMMENT '计划数量',
    completed_qty   INT             NOT NULL DEFAULT 0 COMMENT '完成数量',
    defective_qty   INT             NOT NULL DEFAULT 0 COMMENT '不良品数量',
    unit            VARCHAR(16)     NOT NULL DEFAULT '件' COMMENT '单位',
    plan_start_time DATETIME        DEFAULT NULL COMMENT '计划开始时间',
    plan_end_time   DATETIME        DEFAULT NULL COMMENT '计划结束时间',
    actual_start_time DATETIME      DEFAULT NULL COMMENT '实际开始时间',
    actual_end_time DATETIME        DEFAULT NULL COMMENT '实际结束时间',
    status          VARCHAR(32)     NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING-待分配, ASSIGNED-已分配, IN_PROGRESS-进行中, PAUSED-暂停, COMPLETED-已完成, CANCELLED-已取消',
    priority        TINYINT         NOT NULL DEFAULT 0 COMMENT '优先级 0-普通 1-加急 2-特急',
    remark          VARCHAR(512)    DEFAULT NULL COMMENT '备注',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    version         INT             NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_no (task_no, tenant_id),
    KEY idx_order_id (order_id),
    KEY idx_station_id (station_id),
    KEY idx_worker_id (worker_id),
    KEY idx_tenant_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产任务表';

-- 6. 质检记录表
CREATE TABLE IF NOT EXISTS prod_quality_inspection (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    inspection_no   VARCHAR(64)     NOT NULL COMMENT '质检编号',
    order_id        BIGINT          NOT NULL COMMENT '生产工单ID',
    task_id         BIGINT          DEFAULT NULL COMMENT '生产任务ID',
    inspection_type VARCHAR(32)     NOT NULL DEFAULT 'INLINE' COMMENT '质检类型: INLINE-巡检, FINAL-终检, INCOMING-来料检',
    inspect_qty     INT             NOT NULL DEFAULT 0 COMMENT '检验数量',
    pass_qty        INT             NOT NULL DEFAULT 0 COMMENT '合格数量',
    reject_qty      INT             NOT NULL DEFAULT 0 COMMENT '不合格数量',
    defect_types    VARCHAR(512)    DEFAULT NULL COMMENT '缺陷类型(JSON数组)',
    defect_desc     VARCHAR(1024)   DEFAULT NULL COMMENT '缺陷描述',
    result          VARCHAR(32)     NOT NULL DEFAULT 'PENDING' COMMENT '结果: PENDING-待检, PASS-合格, REJECT-不合格, CONDITIONAL-让步接收',
    inspector_id    BIGINT          DEFAULT NULL COMMENT '质检员ID',
    inspector_name  VARCHAR(64)     DEFAULT NULL COMMENT '质检员姓名',
    inspection_time DATETIME        DEFAULT NULL COMMENT '质检时间',
    remark          VARCHAR(512)    DEFAULT NULL COMMENT '备注',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_inspection_no (inspection_no, tenant_id),
    KEY idx_order_id (order_id),
    KEY idx_task_id (task_id),
    KEY idx_tenant_result (tenant_id, result)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='质检记录表';

-- 7. 报工记录表
CREATE TABLE IF NOT EXISTS prod_production_report (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id       BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    report_no       VARCHAR(64)     NOT NULL COMMENT '报工编号',
    order_id        BIGINT          NOT NULL COMMENT '生产工单ID',
    task_id         BIGINT          NOT NULL COMMENT '生产任务ID',
    station_id      BIGINT          DEFAULT NULL COMMENT '工位ID',
    worker_id       BIGINT          NOT NULL COMMENT '工人ID',
    worker_name     VARCHAR(64)     NOT NULL COMMENT '工人姓名',
    report_qty      INT             NOT NULL DEFAULT 0 COMMENT '报工数量',
    qualified_qty   INT             NOT NULL DEFAULT 0 COMMENT '合格数量',
    defective_qty   INT             NOT NULL DEFAULT 0 COMMENT '不良品数量',
    work_hours      DECIMAL(8,2)    DEFAULT NULL COMMENT '工时(小时)',
    report_time     DATETIME        NOT NULL COMMENT '报工时间',
    remark          VARCHAR(512)    DEFAULT NULL COMMENT '备注',
    create_by       VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by       VARCHAR(64)     DEFAULT NULL COMMENT '更新人',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_report_no (report_no, tenant_id),
    KEY idx_order_id (order_id),
    KEY idx_task_id (task_id),
    KEY idx_worker_id (worker_id),
    KEY idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报工记录表';